#!/usr/bin/env bash
# DESCRIPTION
#   Declare project variable to be used by other scripts
#
# USAGE
#   Other script need to include this file:
#     . envrc
#
# @author: Édouard Lopez <dev+project@edouard-lopez.com>

scriptDir="$(dirname "$0")" # emplacement du script
resourcesDir="${scriptDir%/*}"

# Saxon
HPF_SAXON_DIR="$resourcesDir/saxon"
HPF_SAXON_JAR="$HPF_SAXON_DIR/saxon9he.jar"

# XSLT
HPF_XSLT_DIR="$resourcesDir/xslt"
HPF_XSLT_CSV2SVG="$HPF_XSLT_DIR/csv2svg.xsl"


# Unihan Resources
HPF_UNIHAN_DIR="$resourcesDir/unihan"
HPF_UNIHAN_READING="$HPF_UNIHAN_DIR/Unihan_Readings.txt"

# Templates
HPF_TPL_DIR="$resourcesDir/tpl"
HPF_TPL_SVGTEXT="$resourcesDir/tpl/svg.text-x###.svg.tpl"
HPF_TPL_SVGPATH="$resourcesDir/tpl/svg.path-x###.svg.tpl"

# SVG
HPF_SVG_DIR="$resourcesDir/svg"
HPF_SVGTEXT_DIR="${HPF_SVG_DIR}-text"
HPF_SVGFONT_DIR="${HPF_SVG_DIR}-font"

# TMP
HPF_TMP_DIR="$resourcesDir/tmp"
HPF_UNIHAN_READING_SHORT="$HPF_TMP_DIR/unicode-pinyin.csv"
